- name: demo on simple playbook
  hosts: all
  vars:
    a: 100
  tasks:
   - name: Task1
     ansible.builtin.debug:
        msg: 'hello from playbook Task1 - {{a}}'
   - name: Task2
     ansible.builtin.debug:
         msg: 'hello from playbook Task2'

