- name: Play Level Variables
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name : Task1
      ansible.builtin.debug:
          msg: URL task1 - {{URL}}
    - name: Task2
      ansible.builtin.debug:
              msg: URL task2 - {{URL}}
